
export default {

    beb36: { fontSize: 36, fontFamily: 'BebasNeue-Regular' },
    beb32: { fontSize: 32, fontFamily: 'BebasNeue-Regular' },
    beb30: { fontSize: 30, fontFamily: 'BebasNeue-Regular' },
    beb28: { fontSize: 28, fontFamily: 'BebasNeue-Regular' },
    beb26: { fontSize: 26, fontFamily: 'BebasNeue-Regular' },
    beb24: { fontSize: 24, fontFamily: 'BebasNeue-Regular' },
    beb22: { fontSize: 22, fontFamily: 'BebasNeue-Regular' },
    beb20: { fontSize: 20, fontFamily: 'BebasNeue-Regular' },
    beb18: { fontSize: 18, fontFamily: 'BebasNeue-Regular' },
    beb16: { fontSize: 16, fontFamily: 'BebasNeue-Regular' },
    beb15: { fontSize: 15, fontFamily: 'BebasNeue-Regular' },
    beb14: { fontSize: 14, fontFamily: 'BebasNeue-Regular' },
    beb13: { fontSize: 13, fontFamily: 'BebasNeue-Regular' },
    beb12: { fontSize: 12, fontFamily: 'BebasNeue-Regular' },
    beb11: { fontSize: 11, fontFamily: 'BebasNeue-Regular' },
    beb10: { fontSize: 10, fontFamily: 'BebasNeue-Regular' },

   int46: { fontSize: 46, fontFamily: 'Inter-Regular' },
   int30: { fontSize: 30, fontFamily: 'Inter-Regular' },
   int28: { fontSize: 28, fontFamily: 'Inter-Regular' },
   int26: { fontSize: 26, fontFamily: 'Inter-Regular' },
   int24: { fontSize: 24, fontFamily: 'Inter-Regular' },
   int22: { fontSize: 22, fontFamily: 'Inter-Regular' },
   int20: { fontSize: 20, fontFamily: 'Inter-Regular' },
   int18: { fontSize: 18, fontFamily: 'Inter-Regular' },
   int16: { fontSize: 16, fontFamily: 'Inter-Regular' },
   int15: { fontSize: 15, fontFamily: 'Inter-Regular' },
   int14: { fontSize: 14, fontFamily: 'Inter-Regular' },
   int13: { fontSize: 13, fontFamily: 'Inter-Regular' },
   int12: { fontSize: 12, fontFamily: 'Inter-Regular' },
   int11: { fontSize: 11, fontFamily: 'Inter-Regular' },
   int10: { fontSize: 10, fontFamily: 'Inter-Regular' },

    fs46: { fontSize: 46, fontFamily: 'NotoSans-Regular' },
    fs30: { fontSize: 30, fontFamily: 'NotoSans-Regular' },
    fs28: { fontSize: 28, fontFamily: 'NotoSans-Regular' },
    fs26: { fontSize: 26, fontFamily: 'NotoSans-Regular' },
    fs24: { fontSize: 24, fontFamily: 'NotoSans-Regular' },
    fs22: { fontSize: 22, fontFamily: 'NotoSans-Regular' },
    fs20: { fontSize: 20, fontFamily: 'NotoSans-Regular' },
    fs18: { fontSize: 18, fontFamily: 'NotoSans-Regular' },
    fs16: { fontSize: 16, fontFamily: 'NotoSans-Regular' },
    fs15: { fontSize: 15, fontFamily: 'NotoSans-Regular' },
    fs14: { fontSize: 14, fontFamily: 'NotoSans-Regular' },
    fs13: { fontSize: 13, fontFamily: 'NotoSans-Regular' },
    fs12: { fontSize: 12, fontFamily: 'NotoSans-Regular' },
    fs11: { fontSize: 11, fontFamily: 'NotoSans-Regular' },
    fs10: { fontSize: 10, fontFamily: 'NotoSans-Regular' },

    fs50B: { fontSize: 46, fontFamily: 'NotoSans-Bold' },
    fs46B: { fontSize: 46, fontFamily: 'NotoSans-Bold' },
    fs30B: { fontSize: 30, fontFamily: 'NotoSans-Bold' },
    fs28B: { fontSize: 28, fontFamily: 'NotoSans-Bold' },
    fs26B: { fontSize: 26, fontFamily: 'NotoSans-Bold' },
    fs24B: { fontSize: 24, fontFamily: 'NotoSans-Bold' },
    fs22B: { fontSize: 22, fontFamily: 'NotoSans-Bold' },
    fs20B: { fontSize: 20, fontFamily: 'NotoSans-Bold' },
    fs18B: { fontSize: 18, fontFamily: 'NotoSans-Bold' },
    fs16B: { fontSize: 16, fontFamily: 'NotoSans-Bold' },
    fs15B: { fontSize: 15, fontFamily: 'NotoSans-Bold' },
    fs14B: { fontSize: 14, fontFamily: 'NotoSans-Bold' },
    fs13B: { fontSize: 13, fontFamily: 'NotoSans-Bold' },
    fs12B: { fontSize: 12, fontFamily: 'NotoSans-Bold' },
    fs11B: { fontSize: 11, fontFamily: 'NotoSans-Bold' },
    fs10B: { fontSize: 10, fontFamily: 'NotoSans-Bold' },

    fs46L: { fontSize: 46, fontFamily: 'NotoSans-Light' },
    fs30L: { fontSize: 30, fontFamily: 'NotoSans-Light' },
    fs28L: { fontSize: 28, fontFamily: 'NotoSans-Light' },
    fs26L: { fontSize: 26, fontFamily: 'NotoSans-Light' },
    fs24L: { fontSize: 24, fontFamily: 'NotoSans-Light' },
    fs22L: { fontSize: 22, fontFamily: 'NotoSans-Light' },
    fs20L: { fontSize: 20, fontFamily: 'NotoSans-Light' },
    fs18L: { fontSize: 18, fontFamily: 'NotoSans-Light' },
    fs16L: { fontSize: 16, fontFamily: 'NotoSans-Light' },
    fs15L: { fontSize: 15, fontFamily: 'NotoSans-Light' },
    fs14L: { fontSize: 14, fontFamily: 'NotoSans-Light' },
    fs13L: { fontSize: 13, fontFamily: 'NotoSans-Light' },
    fs12L: { fontSize: 12, fontFamily: 'NotoSans-Light' },
    fs11L: { fontSize: 11, fontFamily: 'NotoSans-Light' },
    fs10L: { fontSize: 10, fontFamily: 'NotoSans-Light' },

    fs46SB: { fontSize: 46, fontFamily: 'NotoSans-SemiBold' },
    fs30SB: { fontSize: 30, fontFamily: 'NotoSans-SemiBold' },
    fs28SB: { fontSize: 28, fontFamily: 'NotoSans-SemiBold' },
    fs26SB: { fontSize: 26, fontFamily: 'NotoSans-SemiBold' },
    fs24SB: { fontSize: 24, fontFamily: 'NotoSans-SemiBold' },
    fs22SB: { fontSize: 22, fontFamily: 'NotoSans-SemiBold' },
    fs20SB: { fontSize: 20, fontFamily: 'NotoSans-SemiBold' },
    fs18SB: { fontSize: 18, fontFamily: 'NotoSans-SemiBold' },
    fs16SB: { fontSize: 16, fontFamily: 'NotoSans-SemiBold' },
    fs15SB: { fontSize: 15, fontFamily: 'NotoSans-SemiBold' },
    fs14SB: { fontSize: 14, fontFamily: 'NotoSans-SemiBold' },
    fs13SB: { fontSize: 13, fontFamily: 'NotoSans-SemiBold' },
    fs12SB: { fontSize: 12, fontFamily: 'NotoSans-SemiBold' },
    fs11SB: { fontSize: 11, fontFamily: 'NotoSans-SemiBold' },
    fs10SB: { fontSize: 10, fontFamily: 'NotoSans-SemiBold' },

};
