import { StyleSheet } from "react-native";
import { Colors } from "@constants";

export default styles = StyleSheet.create({
  headerContainer: {
    flex: 0.1,
    flexDirection: "row",
    alignItems: "center",
  },
  backIcon: { height: 24, width: 24, marginRight: 12, left: 15 },
  inputContainer: { marginHorizontal: 16, marginTop: 12 },
  input: {
    textAlignVertical: "top",
    paddingTop: 10,
    // maxHeight: 120,
    minHeight: 120,
    maxHeight: 120,
    marginVertical: 6,
    paddingLeft: 14,
    // paddingVertical: 0,
    marginBottom: 100,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: Colors.white,
    borderColor: Colors.gray300,
    shadowColor: "rgba(16,24,40,0.05)",
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 1,
  },
  buttonContainer: {
    flex: 1,
    justifyContent: "flex-end",
    marginBottom: 10,
    marginHorizontal: 16,
    marginTop: '40%'
  },
  passWordInput: {
    marginTop: 10,
    height: 44,
    marginVertical: 6,
    paddingLeft: 14,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: Colors.white,
    borderColor: Colors.gray300,
    shadowColor: "rgba(16,24,40,0.05)",
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 1,
  },
  deleteAccountContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.white,
  },
  mainWrapper: { flex: 1, backgroundColor: Colors.white },
  deletAccountText: { flex: 0.9 },
  deleteReason: { flex: 0.9, marginTop: 15 },
  deleteDetail: {
    flex: 0.8,
    marginTop: 30,
    paddingHorizontal: 16,
  },
  inputMargin: { marginTop: 6, justifyContent: 'center' },
  marginTop: { flex: 0.2, marginTop: 20 },
  fontWeight: { fontWeight: "400" },
  fontWeight500: { fontWeight: "500" },
});
